name: ChestShopInfo
main: com.JOO.ChestShopInfo.ChestShopInfo
loadbefore: [ChestShop]

version: 1.0
commands:
  chestshop:
    description: Informationen über ein Chetsshop
    usage: /chestshop mit Blick auf ein Shopschild.	
  shopinfo:
    description: Informationen über ein Chetsshop
    usage: /shopinfo mit Blick auf ein Shopschild.	
